### ISSUE TITLE
[Xcode 7] Every time I try to inject Xcode crashed with unrecognized selector error (targetsInAllProjectsForFileReference::)

### ISSUE THREAD

**Issue by antongaenko** [DyCI/dyci-xcode-plugin#1]
Great plugin, use it regularly, but with Xcode 7 it starts crash it. Here is crash log

Process:               Xcode [2047]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.0 (8227)
Build Info:            IDEFrameworks-8227000000000000~2
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [2047]
User ID:               501

Date/Time:             2015-09-17 13:34:22.612 +0300
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        0519AA51-2037-0D40-40D9-3F5DA1C13FBD

Time Awake Since Boot: 6800 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
Sending recompileAndInject: to <SFDYCIPlugin: 0x7ffc7a5c6b70> from <NSMenuItem: 0x7ffc7a565df0 Recompile and inject>
ProductBuildVersion: 7A220
UNCAUGHT EXCEPTION (NSInvalidArgumentException): +[PBXProject targetsInAllProjectsForFileReference:justNative:]: unrecognized selector sent to class 0x10a2ba550
UserInfo: (null)
Hints: 
  0: Sending recompileAndInject: to <SFDYCIPlugin: 0x7ffc7a5c6b70> from <NSMenuItem: 0x7ffc7a565df0 Recompile and inject>
Backtrace:
  0  0x00007fff8ab12024 **exceptionPreprocess (in CoreFoundation)
  1  0x00000001005f0744 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff9496676e objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff8ab14fad +[NSObject(NSObject) doesNotRecognizeSelector:](in CoreFoundation)
  4  0x00007fff8aa5ae24 ___forwarding_** (in CoreFoundation)
  5  0x00007fff8aa5a998 _CF_forwarding_prep_0 (in CoreFoundation)
  6  0x000000010dfe2817 -[SFDYCIXCodeHelper targetInOpenedProjectForFileURL:](in SFDYCIPlugin)
  7  0x000000010dfe9857 -[SFDYCIXcodeObjectiveCRecompiler canRecompileFileAtURL:](in SFDYCIPlugin)
  8  0x000000010dfefe7d -[SFDYCICompositeRecompiler recompileFileAtURL:completion:recompilers:](in SFDYCIPlugin)
  9  0x000000010dfefc23 -[SFDYCICompositeRecompiler recompileFileAtURL:completion:](in SFDYCIPlugin)
 10  0x000000010dfeb690 -[SFDYCIPlugin recompileAndInjectAfterSave:](in SFDYCIPlugin)
 11  0x000000010dfeb2ed -[SFDYCIPlugin recompileAndInject:](in SFDYCIPlugin)
 12  0x00007fff8809fcd7 _os_activity_initiate (in libsystem_trace.dylib)
 13  0x00007fff882faeb1 -[NSApplication sendAction:to:from:](in AppKit)
 14  0x0000000100bc2ea0 __37-[DVTApplication sendAction:to:from:]_block_invoke (in DVTKit)
 15  0x00000001005f0482 DVTInvokeWithFailureHint (in DVTFoundation)
 16  0x0000000100a942d7 -[DVTApplication sendAction:to:from:](in DVTKit)
 17  0x00007fff882fac4e -[NSMenuItem _corePerformAction](in AppKit)
 18  0x00007fff882fa97c -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:](in AppKit)
 19  0x00007fff8809fcd7 _os_activity_initiate (in libsystem_trace.dylib)
 20  0x00007fff882f98ad -[NSMenu performKeyEquivalent:](in AppKit)
 21  0x0000000101806ab6 -[IDEApplication sendEvent:](in IDEKit)
 22  0x00007fff8812cb68 -[NSApplication run](in AppKit)
 23  0x00007fff880a9244 NSApplicationMain (in AppKit)
 24  0x00007fff88ff75c9 start (in libdyld.dylib)

Performing @selector(recompileAndInject:) from sender NSMenuItem 0x7ffc7a565df0
abort() called

**Comment by PaulTaykalo** [comment]
Reproduced here. Will try to fix ASAP. Thanks for the feedback,

**Comment by PaulTaykalo** [comment]
Hi, @Just- here's update for Xcode 7.0  
Please check it 66efa28ac694ddc77c7a37998d65e0ff0733aaf4
Works on my machine. Should work on yours also

**Comment by antongaenko** [comment]
@PaulTaykalo it works! Thank you! :beers: :pizza: :smile:
